'use strict';

// Bundles the Supabase migrations into public/sandbox/schema.sql for the in-browser demo (/demo).
// The demo runs the same SQL in PGlite (Postgres compiled to WebAssembly), so the policy engine,
// approvals and row level security behave exactly like production. demo-boot.sql stands in for the
// parts Supabase provides (auth.uid(), the anon/authenticated roles, storage tables).
// Runs on `npm start` and as the Vercel build command, so the bundle never drifts from the migrations.

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const migrations = path.join(root, 'supabase', 'migrations');
const files = fs.readdirSync(migrations).filter((f) => f.endsWith('.sql')).sort();

const parts = [`-- Generated by scripts/build-demo.js. Do not edit.\n`, fs.readFileSync(path.join(__dirname, 'demo-boot.sql'), 'utf8')];
for (const f of files) parts.push(`\n-- ${f}\n`, fs.readFileSync(path.join(migrations, f), 'utf8'));

const out = path.join(root, 'public', 'sandbox', 'schema.sql');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, parts.join('\n'));
console.log(`demo schema: ${files.length} migrations -> ${path.relative(root, out)}`);
